# Generated by Django 5.2.5 on 2025-08-27 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Birim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
                ('aciklama', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sikayet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200)),
                ('aciklama', models.TextField()),
                ('durum', models.CharField(choices=[('Yeni', 'Yeni'), ('Yönlendirildi', 'Yönlendirildi'), ('İşlemde', 'İşlemde'), ('Çözüldü', 'Çözüldü'), ('Reddedildi', 'Reddedildi')], default='Yeni', max_length=20)),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True)),
                ('dosya', models.FileField(blank=True, null=True, upload_to='sikayet_dosyalari/')),
                ('ilgili_birim', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sikayetler', to='sikayetler.birim')),
                ('olusturan_kullanici', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Aksiyon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aciklama', models.TextField()),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('yapan_kullanici', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sikayet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aksiyonlar', to='sikayetler.sikayet')),
            ],
        ),
    ]
